### PR TITLE
LPS-64508 - Icon angle-down visible in desktop

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by natecavanaugh** [comment]
Heya Marcos,
Is it possible to assign the value output from `<@liferay_aui:icon >` using the lexicon markupview to the variable?

**Comment by marcoscv-work** [comment]
Of course! ;) !

**Comment by marcoscv-work** [comment]
resend here:
https://github.com/natecavanaugh/liferay-portal/pull/3929

**Pull request closed without merging**
