### PR TITLE
LPS-41647 Update tests to reflect the correct success message

### PR DESCRIPTION
**Pull request by brandizzi**
Hey Nate!

Given the smallness of this pull request, its two reviews already done and busyness of the BP team, I'm sending it directly to you instead of sending to @brunobasto. I tested it and it works. Don't worry, it is an exception, I'll keep sending PRs to Bruno ;)

Thanks!

### CODE REVIEW

**Comment by brandizzi** [comment]
@vicnate5 The commit https://github.com/brandizzi/liferay-portal/commit/db3f601902180f4b2f26103b510aae2ed18673aa has some changed on the POSHI tests made by Sam. I believe they are clearly correct. Yet, I'm notifying you since it is the first time we are sending a PR with POSHI changes without passing by you.

Thanks for the attention!

**Comment by vicnate5** [comment]
@brandizzi Awesome. Yea, it looks correct. Thanks @SamZiemer for fixing the tests as well! @sharonchoi

**Comment by sharonchoi** [comment]
Thanks @SamZiemer! We'll take notice if any other tests need to be updated.

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/32448
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/76df152374...db3f601902

**Pull request closed without merging**
