### PR TITLE
LPS-52984

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-52984.

NOTE:  I decided to standardize the colors we use by using the values defined in Bootstrap (https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/themes/_styled/css/_aui_variables.scss).

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya guys, reassigning it back to Mike: @mbradford89 can we remove the `!important` rule? It makes it harder for end developers to theme. Can we use a higher specificity for that one, or is there some other reason why we can't overwrite it normally? Thanks!

**Comment by mjbradford89** [comment]
Hi Nate,

I think had added so that it would override the ```!important``` in this rule: https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/themes/_styled/css/_liferay_custom.scss#L67

Would it be an option to remove the ```important``` declarations from _liferay_custom.scss?

**Comment by natecavanaugh** [comment]
Heya Mike,
I think that was my fault. I believe I was going to remove it as part of my formatting for LPS-52742 but must have forgotten. Can you remove those along with your commit and resend it?

Thanks Mike!

**Comment by mjbradford89** [comment]
Will do. Thanks Nate!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/natecavanaugh/liferay-portal/pull/3086

**Pull request closed without merging**
