### PR TITLE
LPS-63495

### PR DESCRIPTION
**Pull request by Ithildir**
Hi Nate!
@marcoscv-work suggested me to ask you if you have any idea about these CI failures (especially the sprite generation error, which I think is the root cause)... I tried a few days ago, but I wasn't able to reproduce the problem locally :confused:

I'll try again tomorrow (I didn't today, unfortunately I'm too busy with the RC release), but in the meantime I'm sending this to you, maybe it's a very simple mistake that I totally missed :sweat_smile: 

Thank you!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Andrea,
Could you let me know which CI errors you're hitting? Do we have any examples?

Thanks!

**Comment by Ithildir** [comment]
Sure! Here is the results of the tests I ran yesterday on CI: https://github.com/Ithildir/liferay-portal/pull/264#issuecomment-191032238

**Comment by natecavanaugh** [comment]
Thanks Andrea. However, I can't find the SpriteGeneration error (clicking on the test details doesn't give me much info, as some of the pages are gone).

Do you have a direct link to the error and/or failed test specifcally?

Thanks!

**Comment by Ithildir** [comment]
It's in the `testScanXMLLog` errors: https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=13,label_exp=!master/28878/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

**Comment by natecavanaugh** [comment]
Heya Andrea,
Thanks for sending me that. TBH, I really don't know why that would happen. I'm not seeing anything wrong with your code, though.

Is there something specifically you wanted me to test with this?

**Comment by Ithildir** [comment]
It's a strange problem: because of that sprite generation error, the theme is not applied and the Poshi tests fail :confused: 

I'll keep looking into the sprite generation code, I really don't think that NPE is normal... @marcoscv-work told me you dealt with other sprite problems in the past, so I didn't know if this was something you already encountered.

**Comment by natecavanaugh** [comment]
Heya Andrea,
Okay, the only thing I can think of is that the user theme is deployed via the node build tools (let me know if this is not the case).
But if it is, we don't generate the sprite images in the themes, but in 6.2, they're automatically created on deploy.
I'm not sure which part of the process is trying to access the sprite (if it's just the tests or if it's something else), but that's probably where the issue might be...

**Comment by Ithildir** [comment]
I think the problem happens when the themes are being deployed, it's probably an issue with `ImageIO`... I'm taking some time today to investigate :eyes:

**Pull request closed without merging**
