### PR TITLE
LPS-54042

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-54042 Hey Nate, I think you discussed with Dave about reviewing this portlet

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Mika,
I did. We can take a look at it, but right now, it's actually not working for me as there's no table for it:
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.sacpentry' doesn't exist
```
Is there anything I need to do to get it to generate (I've already run ant all, but not sure if it requires something else).
Thanks Mika,

**Comment by mikakoivisto** [comment]
It should autogenerate the tables otherwise it wouldn't pass CI build. Try with empty database.

**Comment by natecavanaugh** [comment]
Heya Mika,
I tried with an empty DB, but no go. With the CI build, I think it's only running the ant all, which does work fine for me. The error doesn't happen until I actually go to access that portlet in the Control Panel.
So I could see it passing the CI build without the tables being generated.
Is there some step I'm missing?

**Comment by mikakoivisto** [comment]
I really don't know why it's not working for you. I just rebased this branch against latest master, dropped my database and created a new empty database. Then I started the portal after ant all and once the portal was running I went to the portlet in CP and added a new SAC Profile successfully. I'll ask Albert from QA to help you out.

**Comment by natecavanaugh** [comment]
Heya Mika, see https://github.com/mikakoivisto/liferay-portal/pull/65. Let me know if you have any questions. Thanks!

**Pull request closed without merging**
