### PR TITLE
LPS-61952 Toggle-switch help message should be wrapped and placed after the toggle

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:

**Comment by jbalsas** [comment]
Hey @natecavanaugh, this is still missing a big portion of the Lexicon input design like [input-group-default](http://liferay.github.io/lexicon/content/form-elements-input-groups/#input-group-default).

The markup for this, however, is not very consistent with the one for the [basic form elements](http://liferay.github.io/lexicon/content/form-elements/) which makes generating and maintaining it a bit of a headache.

Could you take a look at those to see if there's a way to reconcile them, or at least get them closer? If not, maybe it would be best if you can look around `aui/input/page.jsp` to properly adapt the styling.

Thanks!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/35889
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/d5b05878cf...667ecf65fe

**Pull request closed without merging**
