### PR TITLE
LPS-59810 Dont override label styling coming from the theme

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Nate,

I'm specially sending this to you since I've found some inconsistencies/overriding inside forms.

For one, label styling is getting overridden (see last commit). Not sure how you want to handle that, so feel free to drop that and fix it however you think best. 

Additionally, there seems to be different `_form-validation` mixins applying at the same time. You can see it in journal while creating a new article. Some fields (the ddm ones) will drop a shadow while the rest won't. I didn't even try to fix this since I think I lack the proper context to know what's going on, but let me know if I can help you with something.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by natecavanaugh** [comment]
Heya Chema,
I'm going to partially roll back that last commit (it seems like the position relative was meant to be included with the change to the `ftl` file).
For the other two bugs you mentioned, Patrick actually has fixes that he's waiting on me to review in Lexicon, so once those go in, the other issues you listed should be taken care of.

Let me know if you have any questions.

Thanks Chema!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/31591

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/jbalsas:eb8e097a7b...1b7da21ac1
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/083bedc4bf...1b7da21ac1

**Comment by jbalsas** [comment]
That was perfect, Nate, thanks a lot!

**Pull request closed without merging**
