### PR TITLE
[TECHNICAL-SUPPORT] LPS-78180 fix value if the field is not localizable

### PR DESCRIPTION
**Pull request by rolandpakai**
Please review and check also if it is feasible as an SDH on DE-38.

Thanks and Regards, Roland

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Hi Roland,
Thanks for sending this over. Was this meant for me? There seems to be some confusion over who this was intended for (based on https://github.com/natocesarrego/liferay-portal/pull/107).

Also, what do you mean by "SDH" and "DE-38"? I'm assuming the second is a ticket, but not sure where to read it, and still not sure about the first.

For the most part, this JS is valid, though the part I don't know about for sure is that the check was there to see if the localizationMap is a string, which either means that was a possibility at one point in time, but was changed, or was just a weird oversight. Do you know when that was introduced and why?

Also, there are some general source formatting issues in here (not caused by you, but they should be cleaned up in general if this is sent through).

Let me know if you would like me to continue reviewing, or if Renato should.

Thanks Roland :)

**Comment by rolandpakai** [comment]
Yes, please forward it to Renato, i messed up your names :) (this was my 100s PR  or so in the last 2 days)
@natocesarrego please review this PR too,
and @natecavanagh thanks for the review and sorry for the inconvenience.

**Comment by natecavanaugh** [comment]
@rolandpakai No problem. I'll make my general changes, and send them over to @natocesarrego :)

Thanks guys!

**Comment by natecavanaugh** [comment]
Sent over to @natocesarrego. Thanks!

**Pull request closed without merging**
