### PR TITLE
LPS-53996

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-53996.

I made this change since only Phoenix (US) and Sonora (Mexico) are the only places that use the MST time zone all year.  All the other MST locations use MST in the winter and MDT in the summer.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Jon,
Should these strings be localized? It seems like depending on the language of the system, Phoenix and Sonora might actually be different (I could be wrong, but I'm not sure).

Also, is there anywhere else in the portal we're doing this? What I mean is, either looping the time zones, or adding in distinguishing details like this?

**Comment by natecavanaugh** [comment]
Regarding the "looping the time zones" question, I realized now that it's in the taglib, so I doubt we're doing it in too many other places, but the other part still stands :)

**Comment by jonmak08** [comment]
Hey @natecavanaugh,

Good catch.  I thought since it was a city it might be the same everywhere, but after checking I think you are right in that it could be different.  I'll add that to the language.properties for localization and update this pull request.

Please let me know if you have any questions.  Thanks!

**Comment by natecavanaugh** [comment]
Okay great, thanks Jon :)

**Comment by jonmak08** [comment]
Hey @natecavanaugh,

I have just updated this pull request with the localized names as requested.

Please let me know if you have any questions.  Thanks!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/29553

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/jonmak08:2d21485094...24a14c7383
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/1c1312b9d8...24a14c7383

**Pull request closed without merging**
