### PR TITLE
LPS-55974 Disable show portlet id by default

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @natecavanaugh 

could you please have a look at this pull when you have a chance?

Thanks a lot!

**Comment by natecavanaugh** [comment]
Hey guys, sorry for the delay.

I'm testing this out, and I'm really confused as to the purpose of this feature change?
screenshot 2015-06-23 16 36 37

Is there some purpose I'm missing? Even using an instanceable portlet ID doesn't really provide any more context about what the end goal for this is.
Could you guys illuminate me?

Thanks guys,

**Comment by juliocamarero** [comment]
Hey Nate, 

Thanks a lot for having a look at the pull. Let me explain you the changes:

for legacy reasons, some portlets still show the portlet ID in their configuration. This was useful in the past because some applications required you to know the portlet ID of another portlet. Currently, I am only aware of this situation for the RSS Feeds of Journal but we do want to remove that feature soon if we have enough time.

See this screenshot as an example:
cursor_and_welcome_-_liferay


For this reason, we wanted to move the portletID to a common place for all the portlets (for those portals that need it) but hide it by default. With the new design, it is shown under the portlet title in the configuration but is hidden with a property by default.


This is the new design we are working on:
select-web-content-2

This is hidden by default anyway, and only portals who need it can enable it in the portal.properties

Once the portletID is not needed anymore, we can hopefully fully remove this.

thanks!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/27669

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/ipeychev:2eaeca7750...a4530dc039
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/00109be3a4...a4530dc039

**Pull request closed without merging**
