### PR TITLE
LPS-61238 Toggle sidebar on searchcontainer element selection

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Nate!

This is the first PR for implementing the lexicon sidebar behaviour for search containers.

The only thing not really working is the `lexicon.sidenav` plugin API for toggling the panels. I tried what I thought could work [here](https://github.com/jbalsas/liferay-portal/commit/6327587148f4971c9f2c9205f78662e804e4f741) but something else is missing. Could you take a look at that?

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Chema,
I have something done (basically, there's a `.toggleNavigation(container)` method), but I'm not sure what you guys wish to have happen in a few different scenarios:

1. If the panel is already open, and you select some items, I imagine the panel should stay open, correct?
2. If the panel was open before you selected some items, should it stay open when unselecting?
3. If you have some items selected, and the panel is shown, if click the info trigger, what should happen?

I think that's it for now.

Thanks Chema :)

**Comment by jbalsas** [comment]
Hey Nate!

I guess this should be up to Ivan, but I think we since there's still work to do after we land this, we can iterate with him over the simplest scenario we can produce now.

1. Yeah, I'd expect the panel to stay open 
2. I'd expect it to get closed in that case
3. The info trigger should always toggle the panel, no matter the current selection

Anyway, I just sent this to you to make sure we have a working API for this (`toggleNavigation` and maybe `getVisibilityState`?). We can work out the details later if you can solve that for us.

Thanks a lot!! :blush:

**Comment by jbalsas** [comment]
Hey Nate!

I just talked to @marcoscv-work and Ivan and it seems there's been a little miscommunication in this case. The info panel should only be toggled when clicking on the info button, so there's no need to handle the container selection. 

Could you just drop the last commit and review the reset and send it to Brian? Once it's there, the @ealonso will complete the journal integration and @robertodiaz will do the same for wiki.

Additionally, Marcos really wants to stress that we're going to need this API in any case to show/hide panels in other places, so we need to keep working on it anyways.

Thanks a lot!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/33399

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/jbalsas:025d20504d...ccca202d27
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/10c834b8ea...ccca202d27

**Pull request closed without merging**
