### PR TITLE
LPS 59878

### PR DESCRIPTION
**Pull request by marcoscv-work**
Hey Nate,

We need a class to create a lot of block decorated, like in next image:

captura de pantalla 2015-10-27 a las 16 50 30

Time ago we had the problem with the naming and finally the class was named for an exclusive box, now we are going to start to provide those decorators in a lot of bloks (sometimes the main container, sometimes tables, etc). @ealonso is going to be able to apply in a lot of places.

I used a class name which is used in classic theme, but please, if you think we can use a better name will be a pleasure change it.

We have added a BG color too.

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya @marcoscv-work 
Could you describe a bit about the purpose of the blocks that have that name?

**Comment by marcoscv-work** [comment]
it's like a 'frame', to mark the limit of the main content. the designer used to say "the content should not be afloat". It's like a box which to frame content.

captura de pantalla 2015-10-27 a las 21 35 05

I don't know how to describe better :-/

**Comment by ealonso** [comment]
Hey @natecavanaugh
Please see https://www.google.com/url?q=https://issues.liferay.com/browse/LPS-58491, I added a few mockup with this box, those was designed by the ux team, so you can see the usage of it

**Comment by natecavanaugh** [comment]
Hey guys,
Thanks for the responses.

To me, this seems almost identical to our cards, and speaking with @pat270, it seems we have already added a background color to cards (he's going to send a pull updating lexicon right now).

I think we should use the `card` classes, but also on the top level div add a subclass for cards called `main-content-card` (basically subclassing the card, so we can style it separately from the other cards if we need to).

So the final markup will look like this:

```
<div class="card-horizontal main-content-card">
	<div class="card-row card-row-padded">
	
	</div>
</div>
```

Let me know if that makes sense for you guys.

If it does, can you close out this pull @marcoscv-work and resend this one with the changes?

Thanks guys,

**Comment by pat270** [comment]
Just another note, I wouldn't use ```card-row card-row-padded``` for this one, Bootstraps grid would probably be more useful inside main-content-card card.

**Comment by marcoscv-work** [comment]
Sounds good!, perfect for us, we only need to know the mark up to use it as soon as possible ;)

Maybe it can be interesting create a new card container class by the moment using an @extend of card class, I'm not fan by extend class but if someone want to change the cards suddenly would change the general container, I think that provide a different class name can help in that.

Anyway what you have said works perfectly.
Thanks guys.

**Comment by ealonso** [comment]
Hey @pat270, @natecavanaugh, @marcoscv-work,

I've added the proposed styles by Nate:

```html
<div class="card-horizontal main-content-card">
    <div class="card-row card-row-padded">

    </div>
</div>
```

And the result is:

new_tag_-_liferay

Mockup from UX team:

new_tag_png__7_documentos__7_paginas_en_total_

If you look both images, you can see that the padding and margin is not correct, so, What styles we should apply to our components?, It should be a global solution, because we are going to use those styles around the portal.

Regards,
Eudaldo.

**Comment by marcoscv-work** [comment]
Hey guys, I think that an extension would be the solution because as Eudaldo has mentioned the class is not exactly the same, sometimes we will need a margin-top, etc.

What do you guys think ?

**Comment by natecavanaugh** [comment]
Heya @ealonso 
Can you describe where you placed those classes (so I can test it out locally to see where the issue might be)?

Also, @marcoscv-work I agree an extension could work, but do we have a set of rules or conditions where we would have variations, like margin-top?
Is there a pattern for when we need things to deviate?

Thanks guys,

**Comment by ealonso** [comment]
Hey @natecavanaugh,

I've placed it in my local, I've just sent a pull https://github.com/natecavanaugh/liferay-portal/pull/3605, you can see the changes on Asset Tags Admin for edit and merge tags.

**Comment by natecavanaugh** [comment]
Awesome, thanks @ealonso!

**Comment by marcoscv-work** [comment]
I think we would only need a extra class like:

```
container-card-i-dont-know-class {
   @extend cardstylesclass

   &.classtomargintop {
      margin-top: 20px;
   }
}
```

**Comment by natecavanaugh** [comment]
@ealonso I was only able to partially reproduce your results.
The margin on top is of course missing, but I'm not getting the alignment issue on the sides with the buttons:
screenshot 2015-11-04 08 45 53

@marcoscv-work Do you know the conditions when we would need the margin vs. when we wouldn't?

That would help me be able to name that class if we need it to be an extension.

Or would every main-content-card need to have margin on the top?

**Comment by marcoscv-work** [comment]
Hey Nate, we have been solving some problems caused by .row classes in some places, maybe it was the aligned problem.

About the margin top, I think we could have 20px always and remove from the design the few cases when we need to remove them.

**Pull request closed without merging**
