### PR TITLE
LPS-65660 - Mobile - Save button is not visible in configuration iFrames

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-65660

Hey @natecavanaugh, this is a huge change. This pull should make all the iframe dialogs usable in ios. I tried to catch all the cases, but probably missed some.

@kenjiheigel @ctampoya  I think this is going to break a lot of tests.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@natecavanaugh, I think you can review it first, and after you're done you can send it my way for potential test fixes.

**Comment by natecavanaugh** [comment]
Heya Patrick,
Can you rebase and resend? I'm getting a rebase error.

Thanks!

**Comment by jbalsas** [comment]
Hey guys, sorry to barge in uninvited... 😞 

First of all, kudos on an amazing and very thorough job!!

That being said, I think this is the kind of change across the board we most usually have problems with, so I thought it might be a good time to rethink how we approach this. Hopefully we can reduce the friction and frustration than more often than not comes out of this and get everyone to pitch in at the same time 😉 

First of all, imho, both of us UI and Theme infrastructure teams should focus on identifying potential issues and defining best practices. This is exactly what I'm imagining went on in the first place here, which is, again, an outstanding job.

Once that's done, every functional team has now UI engineers as well as their own dedicated QA engineers. I believe it is in the best interest for everyone to keep them in the loop (send them their appropriate PRs). 

- For one, we'll better communicate potential issues and spread best practices. 
- On top of that, we'll let teams better manage their workload and allow them to apply these changes on their own terms. 
- Lastly, it will remove the big burden that right now lies on us to just go digging to fix everything everywhere.

For this, off the top of my head, we can count on these guys to help us apply these kind of changes in a more controlled and probably efficient way:

- WEM: Julio Camarero (Lead), Carlos Lancha (UI), Evan Nagayama (QA)
- Collaboration: Sergio Gonzalez (Lead), Ambrín Chaudhary (UI), Sharon Choi (QA)
- Forms and Workflow: Marcellus (Lead), Bruno Basto (UI), Victor Ware (QA)
- Staging: Maté Thurzo (Lead), Levente Hudak (UI), Maria Kispal (QA)

This is specially important now that we have so many functional tests... Kenji can coordinate to produce a global fix when possible, but then he won't have to handle all the different functional test fixes that may come up.

What do you guys think?

**Comment by natecavanaugh** [comment]
Heya @jbalsas,
Thanks for the comment, Chema. I agree with you overall, and I think this is the direction we've all been discussing (since it's going to be a bit more work to do a widespread change once the repos are all split).

There are some concerns I have, which I'm not 100% sure if there's a way to fix all of them, but maybe you have some ideas.

1. There is a large amount of overhead in communication between teams. For instance, I can easily imagine a back and forth between the QA and engineers on each team, possibly even just being able to explain how to reproduce a given bug. This is already sometimes an issue, but it could possibly be exponential.
1. There's no way to guarantee that the person who got the PR is even capable of reviewing it (this happened recently when I sent a PR to Sergio the day he went on vacation... I only found out about it by chance).
1. There's a lot of (potential) JIRA overhead as well (depending on how we handle it, which I have some ideas below).

For the first two points, I don't really have any straight forward ideas on how to solve it. For number 1, it's one of those hard to quantify, but can easily expand to create a nightmare situation for any given person reporting or trying to fix a bug.

I think the common thread amongst all of the points though, is that it does put a disincentive on any dev helping to fix an issue.

For number 3 though, I'm not sure if we've thought through how we should handle situations like this, where we have a general bug across components.
For instance, should we create a single ticket, and add all of the affected components?
One idea was that once each team has theirs fixed, they could remove their component, but I don't think this fits into the JIRA workflow where tickets are resolved and workflowed the way they are.

Which means that we'll need to probably create a single ticket, and have sub-tasks for each component, then label each subtask with the appropriate component, then workflow each of them individually.

In this situation, I can imagine any dev who's just trying to help now has to weight the cost of the fix vs the cost of the bug.

And for cases where a real but unquantifiable value (such as "quality") is pitted against a quantifiable value (time to fix + time that it takes to report all of this), I can tell you which one people will almost always pick.

I say this not as someone who is just plucking at theoretical arguments, but as someone who has seen numerous quality issues in the portal, and many times, the cost of writing the ticket, description, test case, etc. far outweighs the amount of time I have to spend on it, and so I put it off just a little longer.
In theory, this would be solved by training or better practices, but in reality, it hasn't worked for me reliably.
We even have tools (such as the `check-source-formatter` module) to eliminate a lot of these, and yet, there's a surprising amount of code where people have obviously never used it before they pushed in their code.

But, maybe there's a better way which I'm not seeing, or even a path that doesn't require those options.
I merely state it because right now, there are a lot of barriers to improving things across the portal, and I would like to ideally lessen that number, but at the very least, not increase it.

Hopefully all of that makes sense. In spirit, we're definitely on the same page, but I do have concerns about the specifics in actually following that path with issues like this one.

What do you think?

**Comment by jbalsas** [comment]
Hey Nate, thanks a lot for your detailed answer!

I'm glad to know we're at least on the same page in spirit 😉 Of course, I also share your concerns about the real life implications of these changes...

I think the biggest barrier right now is not of specifics or protocols, but of mindset. For as long as I can remember (and of course you can remember way longer...) we've been able to just apply changes across the whole portal in one quick swipe. While I agree this has benefits, it has drawbacks as well. I'd say we'd need to mentally work on:

- Teams _own_ their apps. We need to accept and honour that. It's our job to help them build awesome things, but in the end, they're the ones responsible for their quality.
- Keeping teams in the dark about the new patterns or changes is more expensive in the long term than the cost of getting them to apply the changes themselves.
- Things don't need to get fixed immediately, nor doing it so is always a good thing. Having a proper workflow (team ui engineers validation -> team qa validation -> team lead validation) will probably take longer, but will probably also help ensure quality. We need to lose this sense of immediacy. Think about how many times I've urged you to fix something in the last few months... and how much time you could've actually had 😂 

Of course, we can't expect to find a magic wand to make everything work magically. And as usual, there will be edge cases that will need special attention. In the end, I think it might not be as bad as we imagine, and we'll probably start improving as soon as we start trying. 

What I'd really love is to be at least partially trained in this before we are forced to it by the repo split...

Maybe we could schedule a call to discuss the specific concerns and try to come up with a plan to start shaping this...

**Pull request closed without merging**
