### PR TITLE
LPS-57028 Extract ControlMenu from Dockbar

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @natecavanaugh,

This is just a temporary commit to start extracting the functionality from the Dockbar out into the new ControlMenu. Most of the code will probably be thrown away anyway.

@ealonso and @carloslancha will keep working on rewriting these components and styling everything according to the new lexicon guidelines.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Chema,
When you say "Most of the code will probably be thrown away anyway." Which code do you mean exactly?

I'm trying to get an estimation of how much effort to put into formatting this pull (for instance, we don't want Java logic in the theme templates like is currently in there).

Also, since this pull effectively changes the API massively, should we update the Breaking Changes file, so people are aware of it?

**Comment by natecavanaugh** [comment]
Actually, for the Java code part, I see now it's only in the Control Panel one. But yeah, the other questions I'm still curious about :)

**Comment by jbalsas** [comment]
Hey @natecavanaugh,

I was referring to some of the js modules. The interactions are going to drastically change too, so some of the code will probably become useless. For now we just wanted to __move the code around__ so it becomes clear where it belongs to.

We are aware of the breaking changes, but I don't think we are ready to document those just yet. For example, `dockbar-split` will cease to make sense, but we're not there yet. As for the way we register panels, we plan to provide those as OSGi modules that anyone can register. @ealonso could provide more details about what's to come.

Thanks!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/28331
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/e05cb795d6...e7e794c9cd

**Pull request closed without merging**
