### PR TITLE
DEMO

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Heya Nate,

This is the PR for the Loader.

In order to use it, please extract new SDK based on this PR: https://github.com/natecavanaugh/liferay-plugins/pull/340


To check the demo, please deploy this OSGi module: portal/modules/apps/my-module
and then add quick-note portlet.

You will see it uses another module with dependencies!

Thanks,

**Comment by natecavanaugh** [comment]
Heya Iliyan,
Thanks for sending this over. I was able to get it up and running, and it seems like everything was working, but I do have a question as there is one part I couldn't figure out.

I saw that my-module had a dependency for underscore, and I went to import it in my-component.es.js, but I could never get it to load.
I tried all of the following:
`import _ from ./bower_components/underscore/underscore`
`import _ from bower_components/underscore/underscore`
`import _ from bower_components/underscore/underscore.js`
`import _ from my-module/bower_components/underscore/underscore`

But then I went and looked inside of the .js_cache directory and it's not in there.

Can you share the secret for getting it to load?

Thanks Iliyan,

**Comment by ipeychev** [comment]
Heya Nate,

The right syntax in general should be "import _ from 'my-module/bower_components/underscore/underscore" but in any case,
on top of my head, this component will be not loaded simply because it is not registered in our config file. If you remember, we load only these files, which are registered and their dependencies are know in addition (in order to load them via our combo service).

You will have to embed it directly to the page (for example by specifying it in liferay-portlet.xml)

Thanks,

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/27783

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/ipeychev:d280a0710b...bdec0444c8
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/12710968f4...bdec0444c8

**Pull request closed without merging**
