### PR TITLE
LPS-54490

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
ci:retest

**Comment by blzaugg** [comment]
...Maybe I don't know how this retesting stuff works.

**Comment by natecavanaugh** [comment]
Heya Byran,
You should have run the check-source-formatter script locally with the latest version. If a scenario like that happens where you're up to date and you don't get an error, it could be that the CI server is running an outdated copy (which is what I'm guessing is happening here, because I did fix this issue).
I'm working right now to figure out who to talk to about keeping it updated.
I'm going to revert the latest SF commit that you pushed up, though, because it is valid to have a function whose name starts with is*. Thanks Byran :)

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/25550

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/blzaugg:1dc35d6450...8a1a0b952f
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/eb4e496aa9...8a1a0b952f

**Pull request closed without merging**
