### PR TITLE
LPS-60976 Regenerate

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Bruno, can you upload a screenshot of this issue to JIRA? I'm not sure if this is a DDL/DDM issue or a Lexicon issue.

Thanks :)

**Comment by brunobasto** [comment]
Hey Nate, I don't have my computer right now, but the issue is that instead
of using the label-on and label-off attributes, we ate putting the text
inside the span. And we are doing that because we need to add markup to the
label (to put <b> and stuff like that). Actually, instead of putting the
<b> I'll put that orange asterisk in a future commit.

**Comment by brunobasto** [comment]
Hey @natecavanaugh 

I have uploaded a screenshot to JIRA and here's how our markup looks like

    <div class="form-group form-inline liferay-ddm-form-field-checkbox">
        <div class="checkbox">
            <label class="control-label" for="checkboxField">
                <input class="hide toggle-switch" id="checkboxField" name="checkboxField" type="checkbox" value="true">
                <span aria-hidden="true" class="toggle-switch-bar" >
                    <span class="toggle-switch-handle">Required</span>
                </span>
            </label>
        </div>
    </div>

**Comment by natecavanaugh** [comment]
Thanks a ton Bruno :) I'll review it now!

**Comment by natecavanaugh** [comment]
Heya Bruno,
I re-implemented this slightly differently, after talking with Patrick.
We're going to support this in Lexicon and put a margin on the toggle-switch, pretty much as implemented here. Once it goes in, we can safely remove this, but even with it here, it won't affect anything.
(The reason we chose not to use `text-indent` is because the switch is a min-width of 60px, but it theoretically could be wider, in which case, it would bump, or even cover the text).
You can follow the ticket for us adding support to it here: https://github.com/liferay/lexicon/issues/81
and I submitted this here: https://github.com/brianchandotcom/liferay-portal/pull/32931

Let me know if you have any questions.

Thanks Bruno :)

**Comment by brunobasto** [comment]
Awesome! Thank you, @natecavanaugh 

I thought my solution was kinda hacky. I'm glad your are supporting it in lexicon.

**Pull request closed without merging**
