### PR TITLE
LPS-63171

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-63171.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/37720

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/jonmak08:5cc2164a7e...21a0080a42
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/b374334490...21a0080a42

**Comment by natecavanaugh** [comment]
Heya @jonmak08 and @thektan 
Just a heads up on my changes here: https://github.com/jonmak08/liferay-portal/compare/5cc2164a7e...natecavanaugh:21a0080a42, we should always use `AUI.$` unless we're inside of a `aui:script` tag where the `sandbox` attribute is set to `true`.

Thanks guys!

**Comment by jonmak08** [comment]
Thanks for catching that @natecavanaugh!

**Comment by thektan** [comment]
Thanks @natecavanaugh! I'll keep that in mind!

**Pull request closed without merging**
