### PR TITLE
LPS-62482 Wordsmith.

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/35491

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/brunobasto:9131fc55fe...47e6ddedf9
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/fb44882784...47e6ddedf9

**Comment by natecavanaugh** [comment]
Hey guys, just a heads up:
Please don't hardcode the SVG icons into the files. We have a util for it already. Please check my changes :)

Thanks!

**Comment by brunobasto** [comment]
@fernandosouza 

Thanks, @natecavanaugh

**Comment by fernandosouza** [comment]
Thanks, @natecavanaugh, @brunobasto.

**Pull request closed without merging**
