### PR TITLE
LPS-65325 changes to horizontal and vertical theme

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @marcoscv-work

**Comment by juliocamarero** [comment]
@drewbrokke @pei-jung I have moved the logic from the themes about users to a theme context contributor in the users-admin-web module.

Can you please have a look? 

thanks!

**Comment by natecavanaugh** [comment]
@juliocamarero With moving the user variables out of the unstyled theme, doesn't this technically break backwards compatibility, since any theme that's using those vars will now break?
Or were they only recently added?
Either way, I think we'll have to bump the version on it won't we?

Thanks guys,

**Comment by juliocamarero** [comment]
Hey Nate,

Nothing changes for other themes. Now the same variables are injected
before the execution of init.ftl in the theme.

This just makes the themes lighter and the execution faster, but it's a
transparent change for developers.

**Comment by pei-jung** [comment]
Hey @juliocamarero,

Should we also remove the user variables in the velocity templates (https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/init.vm#L44-L62) in 065fbd9622be3f6d0f37d19d2db2c06a81c77739?

**Comment by natecavanaugh** [comment]
@juliocamarero Thanks for the info. Makes sense :)

@pei-jung I believe 065fbd9 already has those removed? Unless I misunderstood what you meant.

**Comment by pei-jung** [comment]
Hey @natecavanaugh,

Those variables are only removed in the freemarker template `init.ftl` but not the velocity template `init.vm`. I'm not sure if the context contributor will inject the variables to both templates. That's why I wonder if the variables in the velocity should be removed or not.

**Comment by natecavanaugh** [comment]
Ahhh sorry, I misread what you pasted. I'll leave that one to Julio to answer :)

**Comment by pei-jung** [comment]
@natecavanaugh That's alright. I should've just linked the url instead of pasting the whole thing. That way, it's more clear :)

**Comment by juliocamarero** [comment]
Yes, you are right @pei-jung !! Sorry I missed that one! I forgot we still have the vm files.

I just added another commit.

thanks a lot!!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/39130
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/56a88d8909...3e126415c1

**Comment by drewbrokke** [comment]
@juliocamarero thanks for letting us know about this.  

Good catch, @pei-jung!

**Pull request closed without merging**
