### PR TITLE
LPS-55253 Fire event when an Image is selected from the Item Selector

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Are you guys sure you want to fire the imageUploaded event when an item is *selected*?
To me it seems weird that uploaded and selected would be the same event. Is there a reason for not having them as different events?

**Comment by ambrinchaudhary** [comment]
It is true that may not make sense throwing an "imageUploaded" event in both cases (and it is also avery generic name). But as the action in both cases is the same, which is just show a caption, we can rename the event as something like "coverImageAdded", or have two different events, "coverImageUploaded" and "coverImageSelected", and listen to this two events to trigger the same action. I find this last approach more useful, in case someday we want to do a different/extra action for any event. If you are ok, I'll send you a new PR with this changes.

**Comment by ambrinchaudhary** [comment]
new PR sent: https://github.com/natecavanaugh/liferay-portal/pull/3296

**Comment by natecavanaugh** [comment]
Perfect, thanks Ambrin :)

**Pull request closed without merging**
