### PR TITLE
LPS-59233

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-59233.

NOTE: Please see https://issues.liferay.com/browse/LPS-59233?focusedCommentId=675643&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-675643 for more details about this issue.

This fix will fix the issue for the QA test's to pass, but @mjbradford89 is going to create another JIRA ticket to resolve an issue this fix creates in DDM.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jonmak08 @brianchiu @mjbradford89 @natecavanaugh 

I merged this and did not merge in https://github.com/brianchandotcom/liferay-portal/pull/30815

**Comment by brianchiu** [comment]
Awesome. Thanks!

**Comment by jonmak08** [comment]
Closing since this has been merged by @brianchandotcom.

**Pull request closed without merging**
