### PR TITLE
LPS-54485 - Updating references to the deprecated Form Builder

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
/cc @marcellustavares

@juliocamarero,

I know you guys use a modified version of the Form Builder in the Audience Targeting plugin. After this pull request, if the plugin is used in master, references should be updated from "aui-form-builder" to "aui-form-builder-deprecated". Just a head up.

Cheers,

**Comment by juliocamarero** [comment]
Thanks a lot @brunobasto !!! :+1:

**Comment by juliocamarero** [comment]
cc @josebalsas

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/25078
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/ee459bdea4...9779445c35

**Pull request closed without merging**
