### PR TITLE
LPS-66437 Organization pictures do not show up in descriptive or icon view

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke
/cc  @juliocamarero please see d50ee117cbe50c8f379f02fc3d3a33df5b951995. Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/42305
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/2e2c57a31a...5ad90c09fe

**Comment by ealonso** [comment]
Hey @pei-jung,

It would be very useful, if we add a new method in OrganizationImpl to obtain the url like in JournalArticleImpl. So, we can use it in jsps instead of have duplicate code. Could you add this new method to OrganizationImpl?

Please see:

````
@Override
public String getArticleImageURL(ThemeDisplay themeDisplay) {
	if (!isSmallImage()) {
		return null;
	}

	if (Validator.isNotNull(getSmallImageURL())) {
		return getSmallImageURL();
	}

	return themeDisplay.getPathImage() + "/journal/article?img_id=" +
		getSmallImageId() + "&t=" +
			WebServerServletTokenUtil.getToken(getSmallImageId());
}
````

Thanks!!

**Comment by pei-jung** [comment]
@ealonso Sure, I added a new method in OrganizationImpl to get the logo URL.  https://github.com/brianchandotcom/liferay-portal/pull/42430. Thanks!

**Comment by ealonso** [comment]
@pei-jung, thanks you very much!!!!

**Pull request closed without merging**
