### PR TITLE
Moving to OSGI module

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Bruno,
Thanks for all of the changes and sending these over. I do have some questions:

1. I keep getting a spawn EMFILE error when trying to run `npm test`, and I tracked it down to it trying to launch Safari. Are you not getting that issue? And if not, can you run `ulimit -n` and tell me what number you get back? Usually the EMFILE issue is related to that open file limit (OSX defaults to 256, but even with mine set to 2560, I still get the error. If I remove Safari, it works, but I'm curious why you wouldn't get the issue.
2. Related to the browsers, I have Chrome and Firefox installed in ~/Applications, not in /Applications, so it's requiring me to set those environment variables.
Do you know if there's some way we can do this for the user so we can look in different locations, and set it for them if we can find it? (maybe we can have npm test run our own script that first looks in different locations and sets the environment variables before invoking karma? I think karma-chrome-launcher already looks in different locations for Windows). I also filed [an issue](https://github.com/karma-runner/karma/issues/1375) with Karma itself.
3. About some of the mock files, I'm not sure if we'll need to have all of these in here. For instance, Sinon allows us to do this in the test: `Liferay.Language.get = sinon.stub().returnsArg(0);`. I feel like there's a few things in there we could get rid of and just use the mocks, spies and stubs that sinon provides (but you may know better than I do where those places may be; I do think it does make sense to have some of it in a mock file just so we don't have to rewrite it for every test).
4. About the structure and naming, I'm wondering if we should just do it as:
```
/test/
    /ddm_form/
        index.js
```

Only because we already have the name of the component in the dir name, we don't need to distinguish that its a ddm_form test (we might if we end up having multiple tests in ddm_form, but I imagine those names would be something related to the purpose of that specific test - but I'm just thinking out loud now).

Let me know what you think Bruno :)

**Comment by brunobasto** [comment]
Hey Nate, thx for the quick reply.

1. Doesn't happen to me at all. My `ulimit -n` gives me `256`. But I don't think wee need to worry about tests running in Safari right now. When we introduce configurations for our CI, we can use Saucelabs (or whatever) to test against different browsers.

2. I can look into that. If karma-chrome-launcher already does that, I can take a look at their code and it shouldn't be hard to implement.

3. Those mocks I was adding as I was getting errors trying to run a simple test case for DDM. But I can use sinon for that. It'll be better.

4. What I don't like about having a lot of files with the same name (index.js, main.js, main.css) is that it's hard to find them (using Sublime or Eclipse, for example) as list grows bigger: http://cl.ly/image/1F191w141D2Q

Thx :)

**Comment by natecavanaugh** [comment]
Heya Bruno,
Sounds good :)

About the last point, I never have a problem in Sublime, if you type: tst/ddm/main.js it will bring up the right one (I don't think Eclipse does fuzzy matching, but then again, there's a lot Eclipse doesn't do... like load fast ;)

Anyways, we can keep discussing that. For me I prefer having convention based names, as it makes it easier to both create and move and makes 1 less thing to worry about. But that's just me :)

Thanks again Bruno!

**Comment by brunobasto** [comment]
resent https://github.com/natecavanaugh/liferay-portal/pull/3210

**Pull request closed without merging**
