### PR TITLE
LPS-59660 DDM - Half of the screen blanks when dragging element down

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Bruno,
This one seems like it might have the same issue as #3698 since it looks like it's not *just* doing that, do you want to leave it open till we solve the root issue on #3698 or close it until then?

Thanks Bruno,

**Comment by brunobasto** [comment]
hey @natecavanaugh 

No. I'll just remove the "selectstart" part and resend. Thx

**Comment by natecavanaugh** [comment]
Heya @brunobasto 
Also, I can't seem to even reproduce the issue mentioned in the ticket (on either FF or Chrome). Is there some way to reproduce?

Thanks!

**Comment by brunobasto** [comment]
hey @natecavanaugh 

Add a text field with a lot of nested fields. Then try to drag it down and keep your cursor on the bottom edge of the form. It will scroll forever. At some point, all you'll see is a blank page.

I'm gonna resend this one because the issue I'm fixing with this commit really belongs to another ticket.

Thanks

**Pull request closed without merging**
