### PR TITLE
LPS-55080 / LPS-55541 Getting the first day of week from the given java.util.Calendar (instead of changing many tags)

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Since we're changing the default value, will this affect people using the taglib, but that aren't setting the firstDayOfWeek attribute directly?
If so, what will the end effect be?

**Comment by brunobasto** [comment]
@brandizzi

**Comment by brandizzi** [comment]
Yes, it will change the behavior.

`Calendar.SUNDAY-2` is -1. If it is the value of the first day of week, the calendar options will not have a first day of week configuration, as seen here: https://github.com/brunobasto/liferay-portal/blob/5138238657356dd649314bd8a1fbecf647cd0ec2/portal-web/docroot/html/taglib/ui/input_date/page.jsp#L111-L116 If this configuration is not given, then the datepicker users the YUI calendar's default - this default is locale-sensitive (compare https://github.com/yui/yui3/blob/master/src/calendar/lang/calendar-base_de.js with https://github.com/yui/yui3/blob/master/src/calendar/lang/calendar-base_en.js).

**Comment by brandizzi** [comment]
Sorry @natecavanaugh, I wrote a first comment but submitted it by mistake. If you have read the unedited version, now it is complete :)

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/26553
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/7cd7009484...c4873e680f

**Pull request closed without merging**
