### PR TITLE
LPS-55198

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-55198. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Hey guys, this doesn't solve the issue mentioned in the ticket. This positions the close button, but the ticket doesn't say anything about the close button. Also, @westonhancock, when you're adding CSS to fix an issue that should work by default, please include information about why you're adding in more CSS instead of removing the offending CSS, and info about what's causing the bug. Assigning this back to Weston. Thanks guys,

**Comment by westonhancock** [comment]
Hey @natecavanaugh 

The issue in [LPS-55198](https://issues.liferay.com/browse/LPS-55198) is caused by the close button. As I mentioned on the pull I sent to Jon, in 6.2.x the close button has:
```css
@media (max-width: 480px) {
    .aui .modal-header .close {
        margin: -10px; 
    }
}
```
This is not the case in master and without the negative margin the div of the close button is pushed down by the padding that is added for narrow views. In turn it pushes the content div out of the way causing the "misalignment" mentioned in the ticket. This does not happen when the permissions modal is opened from the portlet because the header font is larger so when the close button is repositioned by the added padding it doesn't bleed over into the content div. 

As far as fixing the issue, would you like me to just add the rule listed above back in?

**Comment by natecavanaugh** [comment]
Heya Weston,
That makes sense. Thanks for the info, I'll go ahead and push this in.

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/26241
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/506d422c3f...8882699891

**Pull request closed without merging**
