### PR TITLE
LPS-60278

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-60278.

NOTE: Should we remove all the associated CSS and make this change in other portlets/modules as well or should we make this one change at a time?  I think making this change should affect some of the automated tests as well.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya @mjbradford89 and @jonmak08 , I'm not sure this is right.
If we apply this, then something like the blogs would look like:
screenshot 2015-11-19 13 15 11
Can you tell me where we got this design from?

**Comment by mjbradford89** [comment]
Hey @natecavanaugh,  whoops that's doesn't look right.  I had intended to use the lexicon btn-group class for changing instances like
image
to
image.
But I didn't realize the effect my change would have elsewhere.  Should we not be using that lexicon class in portal or can we update any current styles to target btn-group instead of button-holder?

**Comment by natecavanaugh** [comment]
@mjbradford89 For the "after" picture you added, where did you get that change from, though? The reason I ask is because that second one doesn't look right either, and that entire side panel thing doesn't exist in the Lexicon specifications.
Can you reach out to Juan Hidalgo in the #frontend-dev-lexicon channel in Slack and ask him how he wants to proceed on that (either what the equivalent replacement is, or how he prefers it to look)?
We may need to add CSS in portal that just targets `.button-holder` or possibly even just `.button-holder` when it's inside of that kind of sidebar.

Thanks Mike,

**Comment by mjbradford89** [comment]
Sure I'll reach out to Juan.  That change was from just swapping those two classes.  Thanks Nate!

**Pull request closed without merging**
