### PR TITLE
LPS-62382 - Product menu styles fixes

### PR DESCRIPTION
**Pull request by marcoscv-work**
image

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Marcos,
In the second image, I'm not seeing that issue fixed with these changes.

When I set the window size smaller than 768px, it has the same bug as it did previously.

Can you confirm if you're seeing the same thing?

Thanks Marcos,

**Comment by marcoscv-work** [comment]
I'm taking a look! let me a few minutes! :+1:

**Comment by marcoscv-work** [comment]
Hey @natecavanaugh , the changes are fine, I have not explained well, the problem in mobile was a header alignment and height:

image

control-menu is less high on purpose, I know it can be a little stranger because of horizontal alignments between product menu and control-menu but we decided to reduce control-menu height on purpose

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/34842
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/61e0c09922...379d21ede1

**Pull request closed without merging**
