### PR TITLE
LPS-66732 Makes the user able to scroll simulator content.

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Fernando,
Sorry for the delay, but I'm processing multiple theme pulls right now, and need to do them sequentially.

Could you also send me a pull for 7.0.x?

Thanks Fernando!

**Comment by fernandosouza** [comment]
Hi, Nate.

No problem. I will send you a PR for 7.0.x.

Thank you!

**Comment by fernandosouza** [comment]
@natecavanaugh I can not send the PR to you because your repository doesn't have the branch 7.0.x.

**Comment by natecavanaugh** [comment]
@fernandosouza It should be in the liferay-portal-ee repo to the ee-7.0.x branch. Sorry for not being more clear on that :)

Thanks Fernando!

**Comment by fernandosouza** [comment]
Hello @natecavanaugh. Sorry for the delay. Done! :)
https://github.com/natecavanaugh/liferay-portal-ee/pull/349

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/40957
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/8d82fa7321...fbd3297dea

**Pull request closed without merging**
