### PR TITLE
LPS-77114

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@natecavanaugh , can you or someone in your team source format the *.js files?

Go ahead and send to Brian if you're good with the changes.

Thanks!

**Comment by hhuijser** [comment]
ci:test

**Comment by natecavanaugh** [comment]
@hhuijser Sure thing, I still have them on my computer :)

And sorry for the delay, I'm just now seeing this comment.

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)

**Pull request closed without merging**
