### PR TITLE
LPS-58995 Animated alert message

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Heya @natecavanaugh, could you fwd this pull to Jorge once you're done with your review?

Thanks a lot!

**Comment by natecavanaugh** [comment]
Heya guys,
Sure thing... I do have one concern with it, however, which is with the animation.
Since we're trying to unify the look and feel, my worry is with animating the alert message only in one portlet we could be leaning towards some inconsistency in the UI.
Do you know if Jadson and Juan have discussed this already?

Thanks guys,

**Comment by brunobasto** [comment]
hey @natecavanaugh 

I don't think so. Jadson only told me informally to do this way saying the animation would bring the user attention to the alert. I guess we could get rid of the last commit so that we don't get blocked while de discussion between you, Jadson and Juan goes on. @marcellustavares, what do you think?

**Comment by brunobasto** [comment]
Resent at https://github.com/natecavanaugh/liferay-portal/pull/3625

**Pull request closed without merging**
