### PR TITLE
LPS-59972 Uses new icon for empty message

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by natecavanaugh** [comment]
Heya Eudaldo,
Could you have Marcos or Juan give this to you in SVG format?
Also can you ask them if they prefer for this to be a Liferay only icon, or if it should be part of Lexicon itself. If so, I can move the SVG over to Liferay and use that one.

Thanks Eudaldo,

**Comment by ealonso** [comment]
@marcoscv-work Could you check nate's comment

**Comment by marcoscv-work** [comment]
Hey @natecavanaugh !

This image is an animation, we have decided use gif until know the approach to create new animations in portal. Do you prefer a static image?

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/31718

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/ealonso:894f923e94...af675afd7e
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/2fdb7de654...af675afd7e

**Pull request closed without merging**
