### PR TITLE
LPS-54490

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-54490. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya @brunobasto ,
This seems slightly odd from the API point of view to have getter/setter methods in addition to direct property access.
For instance, when should a developer use `instance._getForm()` instead of `instance.liferayForm`?
Also, having a setter method that doesn't accept anything seems odd as well.

I wonder if we could resolve these by changing the names of the methods to something like:
1.  `_getForm` would instead be something like `_resolveContainerForm`
2. `_setForm` would be something like `_syncFormNode`

Or something like that, I'm not 100% sure, but I'm open to ideas.

What do you think?

**Comment by brunobasto** [comment]
@natecavanaugh Totally agree. This one needs some formatting. I'll resend it

**Comment by natecavanaugh** [comment]
Okay cool, thanks Bruno :)

**Comment by brunobasto** [comment]
@natecavanaugh resent https://github.com/natecavanaugh/liferay-portal/pull/3252

**Pull request closed without merging**
