### PR TITLE
LPS-58051 Lexicon descriptive view in Documents and Media

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Nate,

This pull applies the lexicon descriptive view to Documents and Media.
Let us know if you have any question.

Sergio

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary @robertoDiaz

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
I've created a new PR fixing the SF errors: https://github.com/natecavanaugh/liferay-portal/pull/3477

**Comment by sergiogonzalez** [comment]
Closing because this is the new one: https://github.com/natecavanaugh/liferay-portal/pull/3477

**Pull request closed without merging**
