### PR TITLE
LPS-55048

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-55048. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Jon,
I saw on the ticket in JIRA that it's not prevalent in master, but I can't seem to get it to happen at all. Is there a way to test this?
What I'm really trying to understand is why we need this. What css is causing it to not bold in certain situations?

**Comment by blzaugg** [comment]
@westonhancock, did you have any issues replicating this?

The original fix sent to me by @zxdgoal, had removed the font-weight from a "global" selector. I had him address the issue at a more "local" Web Content selector.

https://github.com/zxdgoal/liferay-portal/commit/940df39307e06fa942d5ca5dc3dc4d9e7e2b81b2

**Comment by westonhancock** [comment]
I didn't have any issue replicating the issue described in [LPS-55048](https://issues.liferay.com/browse/LPS-55048)
hyperlink_wont_bold_master

**Comment by natecavanaugh** [comment]
Hey guys,
It only happens in Chrome, and the global selector only applied to custom_common.css. We should apply the fix in there, since it's only specific to the Classic and Control Panel themes.
Let's move it there.

Thanks guys,

**Comment by zxdgoal** [comment]
Hey @blzaugg

Could you send my original fix to Nate?

I could not resend because I am on PTO and no laptop at hands. 

Many thanks
John

**Comment by natecavanaugh** [comment]
Actually John, your fix is still too global. We need the current rule (scoping it to the html-editor) to be moved into custom.css.

**Comment by blzaugg** [comment]
I'll take care of it. Thanks all.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/natecavanaugh/liferay-portal/pull/3207

**Comment by zxdgoal** [comment]
Thanks, Jon

**Pull request closed without merging**
