### PR TITLE
LPS-67021 - New westerns bank theme

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

image

**Comment by natecavanaugh** [comment]
Heya Marcos,
There is some weird duplication [here](https://github.com/natecavanaugh/liferay-portal/pull/4046/files#diff-5f4a564537e67f228b8552c30c344390R20) and [here](https://github.com/natecavanaugh/liferay-portal/pull/4046/files#diff-5f4a564537e67f228b8552c30c344390R24) (they're both in the same rule with the same media query).
Can you let me know if that's as intended or what it should be?

Thanks Marcos,

**Comment by marcoscv-work** [comment]
Hey @natecavanaugh ! thank you, that's true, I've removed those lines, new PR here:
https://github.com/natecavanaugh/liferay-portal/pull/4047

**Pull request closed without merging**
