### PR TITLE
LPS-55663

### PR DESCRIPTION
**Pull request by westonhancock**
Hey @natecavanaugh 

Here is an update for [LPS-55663](https://issues.liferay.com/browse/LPS-55663).
I've rebased it per your request in natecavanaugh/liferay-portal#3254. Let me know if you have any questions.

### CODE REVIEW

**Comment by westonhancock** [comment]
Hey @natecavanaugh 

I'll take care of the rebase issue really quick and force update this branch.

**Comment by westonhancock** [comment]
rebase issue resolved.

**Comment by natecavanaugh** [comment]
Heya @westonhancock, I'm kicking this one back to you because `A.Array.indexOf` will operate on Arrays and Array-like objects (such as NodeList, DOMLists, etc). This will break for all of files handling uploads (anything using dataTypes.types, since that object is not an Array itself). Can you go through and verify that the data coming into these methods is actually an Array? If it's not, we can skip those for now. Thanks,

**Comment by westonhancock** [comment]
Sure thing.

**Pull request closed without merging**
