### PR TITLE
LPS-60017

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-60017.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Jon,
Can you paste a screenshot of the after style?
Thanks!

**Comment by jonmak08** [comment]
**Before changes**
Before looking up DNS:
before

After looking up DNS:
after


**After Changes**

Before looking up DNS:
welcome liferay

After looking up DNS:
after-search

**Comment by natecavanaugh** [comment]
Awesome, thanks a ton Jon!

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/31636
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/947da262fb...0fe36e3f80

**Pull request closed without merging**
