### PR TITLE
LPS-66609 Update cache

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
@ambrinchaudhary Sorry this is taking so long to get these in, I have 3 or 4 other theme pulls that I'm trying to get in, but if I just send these to Brian one at a time, the rebase will fail, and we'll have to keep resending it over and over.

Also, could you send me an equivalent pull for 7.0.x?

Thanks Ambrin :)

**Comment by ambrinchaudhary** [comment]
@natecavanaugh no problem if we can't still merge this. 
About sending the equivalent for 7.0.x, I thought this was being somehow merged automatically. It is just this kind of changes which we have to send them to that branch? 
Is in `liferay-portal`, branch 7.0.x right? Or in `liferay-portal-ee`? 
Thanks! 
/cc @marcoscv-work

**Comment by natecavanaugh** [comment]
Hi @ambrinchaudhary ,
It used to be merged automatically, however, Brian stopped automatically backporting changes, and he's asked for theme changes to be sent to both branches.
Also the repo would be the liferay-portal-ee, on the ee-7.0.x branch.

Thanks Ambrin :)

**Comment by natecavanaugh** [comment]
Hey guys,
Just pinging you to see if you still wanted to get this pull in. I haven't gotten one on ee-7.0.x. Did you still want to send that one as well?

Thanks!

**Comment by ambrinchaudhary** [comment]
Hey Nate, I was trying to send you today the PR but I had some git problems...will send you tomorrow. Sorry for the delay! :-(

**Comment by ambrinchaudhary** [comment]
This is the PR: https://github.com/natecavanaugh/liferay-portal-ee/pull/356

**Comment by natecavanaugh** [comment]
Sent to Brian as a stacked pull here: https://github.com/brianchandotcom/liferay-portal/pull/41189

**Pull request closed without merging**
