### PR TITLE
LPS-56600 Visual formatting

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by natecavanaugh** [comment]
Heya Bruno,
I'm closing this one out. The main reason is because of the use of lodash.
I've been trying to avoid us mixing libraries like this, and YUI already has all of the functionality in lodash already (this is mainly to avoid causing dependency issues later on).
Can you do the following:
- Use YUI's array methods instead of lodash's
- Instead of using Lang.isArray, we can use the native Array.isArray (and you don't need to create a function wrapper around it, you can pass it directly)
- In the CSS instead of `overflow-x: hidden; overflow-y: hidden;` you can shorten it to `overflow: hidden`.

Let me know if you have any questions. Thanks Bruno!

**Comment by brunobasto** [comment]
resent https://github.com/natecavanaugh/liferay-portal/pull/3347

**Pull request closed without merging**
