### PR TITLE
LPS-62065 Only one control-menu panel should be opened

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya Chema,
Sorry, just a heads up that I'm still looking at this one. When I try to build portal on this pull it keeps running out of memory on startup, but I can't tell if it's just master, or if it's my setup (I don't believe it's anything in the pull itself, though).

I'll let you know if I find out more.

Thanks for your patience :)

**Comment by jbalsas** [comment]
Hey Nate, no problem, just let me know if I can help you in any way :)

**Comment by natecavanaugh** [comment]
Heya Chema,
I've had a chance to look at this a bit more, and do you know why they're using data-target="#someId,#wrapper"?
The data-target isn't meant to have multiple selectors in there (and from what I can tell it doesn't even really do anything for it), and this is why it's reaching the inconsistent state.

Do you know if there's some use case for why this is there that I'm not aware of?

**Comment by jbalsas** [comment]
I asked @juliocamarero the same thing and he said Pattrick did that for them, so I assumed you'd know ;)

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/35721

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/jbalsas:2f21f8600f...21d97c3e8a
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/168b6865aa...21d97c3e8a

**Pull request closed without merging**
