### PR TITLE
LPS-53519

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-53519. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Heya guys, I'm kicking this one back to Travis. Don't we need to update another file, like HotDeployHookListener? From the history, it appears that just modifiying this won't be enough, but I could be wrong. If we don't need to update anything else, can you resend Travis? Thanks guys,

**Comment by travisc5** [comment]
@natecavanaugh , you're right it looks like we need to add the change to that file as well. Since this pull is being compared against master, should I send the pull against 6.2.x and make the change to the HotDeployHookListener? Thanks Nate!

**Comment by travisc5** [comment]
Here is an updated pull for just the 6.2.x branch https://github.com/natecavanaugh/liferay-portal/pull/3117

**Comment by jonmak08** [comment]
Hey @natecavanaugh,

This entry was already added to ```portal-impl/src/com/liferay/portal/deploy/hot/HookHotDeployListener.java``` for liferay-portal/master at https://github.com/liferay/liferay-portal/commit/18d2a2858c41208a1151ea39178c1029aedfdc6e and https://github.com/liferay/liferay-portal/commit/4458037571f0c34b55f302d15437667dcf635dae. 

They were added by https://issues.liferay.com/browse/LPS-45036.

These changes to ```portal-impl/src/com/liferay/portal/deploy/hot/HookHotDeployListener.java``` have not been made to liferay-portal-ee/ee-6.2.x.

Please let me know if you have any questions.  Thanks!

**Comment by travisc5** [comment]
@natecavanaugh ,

I checked HookHotDeployListener.java on ee-6.2.x and @jonmak08 is correct. The changes from liferay@18d2a28 and liferay@4458037 need to be added to this file.

**Comment by travisc5** [comment]
I created https://issues.liferay.com/browse/BPR-3206 to back port the fix from LPS-45036

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/24136
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/55d0bbf32e...30cf24e139

**Pull request closed without merging**
