### PR TITLE
LPS-68543

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @natecavanaugh,

Attached is an update for http://issues.liferay.com/browse/LPS-68543.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Resolved source formatting error.

**Comment by natecavanaugh** [comment]
Heya Jon,
As we discussed, I'm going to kick this one back. I'm not sure this actually solves the case, since the offset only guarantees an arbitrary amount of time, but if the server side takes longer to respond than the offset, it will still be broken, which will lead to weird effects.

Also, adding the additional property will end up adding some API complexity (that we'll also have to support going forward).

@antonio-ortega, can we use some other mechanism to indicate when we've sent an extend and when we've actually extended it on the serverside?

/cc @achaparro

Thanks guys,

**Comment by achaparro** [comment]
Hey @jonmak08, @natecavanaugh,

We have been trying to figure out another way to fix it but we haven't got any clue. Let me explain our thoughts: if someone sets: 
`session.timeout.auto.extend=true`

We have to keep the session alive in the server side only if the user hasn't closed the browser. This means that the server must wait for the auto extend request to extend the session, if this doesn't occur, it should expire the session.

Taking this into account it seems that the only option we have is to give the customers the possibility of sending the auto extend request in advance just if they need it. Maybe we could set the offset default value as 0 so that we don't change the current behaviour by default:
https://github.com/natecavanaugh/liferay-portal/pull/4099/commits/078d54f4f598055cedf1d3686a4f500646ca37a0#diff-70e7a8b9586d2a3f809fcc9e9e22e2b3R2666

Do you have any other idea?

Thanks.

PS: @antonio-ortega

**Comment by achaparro** [comment]
Hey @natecavanaugh,

Did you have the chance to review my comment?

Thanks.

**Comment by jonmak08** [comment]
Hey @achaparro,

@natecavanaugh was at DevCon this past week and I was out on vacation.  I came back yesterday, but did not have a chance to review the comments.  I will get back to you today after reviewing everything.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Hey @achaparro,

So in reviewing these changes, could we not use the offset and just listen for the ```autoExtend``` value instead?  If ```autoExtend = true```, we just set ```hasExpired``` and ```hasWarned``` to false and call ```instance.extend()```?

**Comment by jonmak08** [comment]
I am wondering if the below will work?

```javascript
_startTimer: function() {
	var instance = this;

	var sessionLength = instance.get('sessionLength');
	var warningTime = instance.get('warningTime');

	var registered = instance._registered;

	var interval = 1000;

	instance._intervalId = A.setInterval(
		function() {
			var timeOffset;

			var timestamp = instance.get('timestamp');

			var elapsed = sessionLength;

			if (Lang.toInt(timestamp)) {
				timeOffset = Math.floor((Date.now() - timestamp) / 1000) * 1000;

				elapsed = timeOffset;
			}

			var extend = instance.get('autoExtend');

			var expirationMoment = false;
			var warningMoment = false;

			var hasExpired = elapsed >= sessionLength;
			var hasWarned = elapsed >= warningTime;

			if (extend) {
				hasExpired = false;
				hasWarned = false;
			}

			if (hasWarned) {
				if (timestamp == 'expired') {
					expirationMoment = true;
					hasExpired = true;
				}

				var sessionState = instance.get('sessionState');

				if (hasExpired && sessionState != 'expired') {
					if (extend) {
						hasExpired = false;
						hasWarned = false;
						expirationMoment = false;
						warningMoment = false;

						instance.extend();
					}
					else {
						instance.expire();

						expirationMoment = true;
					}
				}
				else if (!extend && !hasExpired && hasWarned && sessionState != 'warned') {
					instance.warn();

					warningMoment = true;
				}
			}

			for (var i in registered) {
				registered[i](elapsed, interval, hasWarned, hasExpired, warningMoment, expirationMoment);
			}
		},
		interval
	);
},
```

**Comment by jonmak08** [comment]
I can try testing this on Monday to see if I can find any other ways for this.

**Comment by antonio-ortega** [comment]
Hi @jonmak08 ,

I've been having a look at your comment and your code, and I guess when you say:

> If autoExtend = true, we just set hasExpired and hasWarned to false and call instance.extend()

But later, in your code, you write: `            if (extend) {
                hasExpired = false;
                hasWarned = false;
            }`

Maybe you mean: 
`            if (extend) {
                hasExpired = false;
                hasWarned = false; instance.extend();
            }`
Because in other way you're not calling to extend the session.

But anyway, from my understanding, in that case, I'm not sure if that is the best solution because we'll be extending the session every single second (in case interval keep being 1000). Probably the issue will be sorted out, but maybe we are generating too much traffic. Let me know your thoughts.

**Comment by jonmak08** [comment]
I am still testing to see if I can figure out anything.  I will have an update by tomorrow.

**Comment by jonmak08** [comment]
Hey @achaparro and @antonio-ortega,

You are correct, I forgot to call the ```instance.extend()``` call.  This seems to solve the issue I think.  Can you test to make sure?

```javascript
_startTimer: function() {
	var instance = this;

	var sessionLength = instance.get('sessionLength');
	var warningTime = instance.get('warningTime');

	var registered = instance._registered;

	var interval = 1000;

	instance._intervalId = A.setInterval(
		function() {
			var timeOffset;

			var timestamp = instance.get('timestamp');

			var elapsed = sessionLength;

			if (Lang.toInt(timestamp)) {
				timeOffset = Math.floor((Date.now() - timestamp) / 1000) * 1000;

				elapsed = timeOffset;
			}

			var extend = instance.get('autoExtend');

			var expirationMoment = false;
			var warningMoment = false;

			var hasExpired = elapsed >= sessionLength;
			var hasWarned = elapsed >= warningTime;

			if (extend && (hasExpired || hasWarned)) {
				hasExpired = false;
				hasWarned = false;

				instance.extend();
			}

			if (hasWarned) {
				if (timestamp == 'expired') {
					expirationMoment = true;
					hasExpired = true;
				}

				var sessionState = instance.get('sessionState');

				if (hasExpired && sessionState != 'expired') {
					if (extend) {
						hasExpired = false;
						hasWarned = false;
						expirationMoment = false;
						warningMoment = false;

						instance.extend();
					}
					else {
						instance.expire();

						expirationMoment = true;
					}
				}
				else if (!extend && !hasExpired && hasWarned && sessionState != 'warned') {
					instance.warn();

					warningMoment = true;
				}
			}

			for (var i in registered) {
				registered[i](elapsed, interval, hasWarned, hasExpired, warningMoment, expirationMoment);
			}
		},
		interval
	);
},
```

**Comment by antonio-ortega** [comment]
Hi @jonmak08 ,

Sorry, but I can not understand at all how your change works. Could you explain it a little bit to me, please?

I mean, let's suppose next use case:
User has set in web.xml:
 - session-timeout = 1

And in portal-ext.properties:
 - session.timeout.auto.extend=true
 - session.timeout.warning=0

Under this conditions, and after 60 secs (aprox.) our variables would be:
**extend** = true
**sessionLength** = 60000
**warningLength** = 60000
**elapsed** = 60000

That means => **hasExpired** and **hasWarned** are true.

So, in this point I find two issues that I can not understand at all:
**1.-** The small one is that, as far as I understand, we are going to extend session twice very quickly, in the new code introduced by Jon, and in the old code, so probably we'd need to remove the old call to instance.extend(). This is not a big deal.

**2.-** The most important: How is this avoiding the cases like the one reported by our customer? I mean, the problem is not that "extend" function is not called, our problem is that under poor network conditions (among other possible reasons), we are calling too late (whithin the last second of the session), and when that call arrives the server is already expired in this side. With this new change, and sorry if I misunderstood your change, but we are launching that call in the same moment (as maximum, just a few milisecs before). 

So far, we've only found a way to deal with this without performance issues: Extend the session before the moment when we do it now. How much before? It depends on customer environment, so maybe a property to define that value is not such a bad idea.

Thanks!

/cc @achaparro

**Comment by jonmak08** [comment]
Hey @antonio-ortega,

So in reviewing your original changes, maybe I am misunderstanding how it works.  If we set the```sessionExtendOffset = 0```, the ```hasExpired = (elapsedTime + 0 >= sessionLength)``` and ```hasWarned = (elapsedTime + 0 >= warningTime)```.  That would make the sessionLength and the expiration time equal, thus having the same issue no?

If we are trying to accommodate any network conditions or client side issues, the safest way to extending the session with ```session.timeout.auto.extend=true``` would be server side correct?

In regards to my changes, I was thinking that if the ```elapsedTime >= sessionLength``` or ```elapsedTime >= warningTime``` and ```session.timeout.auto.extend=true```, we would extend the session.  We could return early after the session is extended, or I was just setting ```hasExpired = false;``` and ```hasWarned  = false``` so the rest of the code in that block would not fire.

If you are saying that calling ```extend()``` _could_ fire too late, I see your point in cases where the client side is too slow or something goes wrong, but I think any way we try to resolve this, we would have these issues.  The safest way would be on the server side like @natecavanaugh mentioned in the original post.

Thoughts?  Thanks for your help/input and sorry for all the confusion!

FYI, we are on vacation Thursday and Friday, in case I cannot respond, but we can continue this discussion to find a resolution next week.

**Pull request closed without merging**
