### PR TITLE
LPS-69350 - Portlet back link should use Lexicon svg icon

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-69350

Hey @natecavanaugh, I wasn't sure how to use the liferay-ui taglib inside of our velocity templates so I just inlined the svg.

### CODE REVIEW

**Comment by pat270** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
There was a compile error at head earlier. Should be fixed now.

https://loop.liferay.com/home/-/loop/feed/3454339

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/45254

View just my changes: https://github.com/natecavanaugh/liferay-portal/compare/pat270:fcf7c9398b...9a364da86a
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/09886a8094...9a364da86a

**Pull request closed without merging**
