### PR TITLE
LPS-59249 - Form-groups shouldn't be nested within each other, remove uneeded form styles

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-59249

Hey @natecavanaugh @jbalsas, keeping the form-control in the template due to styling issues we are having with Blogs forms.

### CODE REVIEW

**Comment by jbalsas** [comment]
Thanks Patrick!

I'll try to think about a better way to add this without having to manually hardcode alloyeditor in there. I'm not sure Marcellus or Bruno will like this.

I still think we're producing some inconsistent markup by not adding the class to what are actually form controls in some cases, but we have bigger fish to fry.

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/31699
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/38c41fd340...46d1b18e28

**Comment by jbalsas** [comment]
Hey guys, I just realised this is actually removing a bunch of JS inside the template... is that intended or is it coming from a previous removal?

**Comment by natecavanaugh** [comment]
Heya Chema,
Sorry about that, it was a messed up rebase. I've pushed up the reverting of that piece to the branch (and luckily, Brian hasn't reviewed it yet).

**Comment by jbalsas** [comment]
:smile: :+1:

**Comment by natecavanaugh** [comment]
@jbalsas Regarding the `form-control` class thing, I actually agree with you in theory, however, I don't believe the incosistency is ours, but rather in Bootstrap.
For instance, they don't put the `form-control` class on checkboxes or radio inputs, even though, those are form controls. Same for buttons.
Since that is their API, we're choosing to respect it, since not respecting it could lead to some things breaking.

Also, I think the two things you want here are at odds with each other. The reason you added the class `form-control` was initially to make the editor look like inputs, but that also means that if we did that for all parts of a form, then we're possibly adding styling where it doesn't make sense.
What we would need to do is create a brand new class that doesn't have any styling attached to it, but marks every element that is a form control as such, something like `lfr-form-control`.
But even if we did that for semantics, you still want the styling from `form-control`, which means we would still need to conditionally add this class (or, we add in a bunch of styles for html-editor form-controls to undo all of bootstrap's CSS, which just seems excessive, and likely to not really be exhaustive of all of the cases in which form-controls get styling).

Like you said, we do have bigger fish to fry, but hopefully that explains our thinking a bit.
Please feel free to respond though :)

Thanks Chema!

**Comment by jbalsas** [comment]
Thanks Nate, I completely understand it now... shame on Bootstrap then :smile: 

On to the bigger fish :wink:

**Pull request closed without merging**
