### PR TITLE
LPS-77114

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @petershin @jbalsas 

@natecavanaugh, just starting real small and only applying to site-navigation

1. I still get warnings, but don't know how to format:
```
File: src/main/resources/META-INF/resources/js/SiteNavigationMenuEditor.es.js
    Line 61: Functions should only have one return statement
    Line 118: Args should each be on their own line (args on same line): reduce(...)
    Line 166: Args should each be on their own line (args on start line): then(...)
    Line 166: Args should each be on their own line (args on same line): fetch(...)
    Line 166: These arguments should each be on their own line: fetch(this.editSiteNavigationMenuItemParentURL, {
```

2. Is there an option to not autofix, but just show warning (to use for command `checkFormat`)?

**Comment by natecavanaugh** [comment]
Heya Hugo,

> 1. I still get warnings, but don't know how to format:

I can send you a new pull with those changes if you like, since they need to be manually fixed (but I already have them fixed locally, so just let me know).

> 2. Is there an option to not autofix, but just show warning (to use for command checkFormat)?

Yep, just change `"checkFormat": "npm run prettier...."` to `"checkFormat": "npm run csf"`, and you'll be all set :)

Let me know if you have any other questions.

Thanks Hugo,

**Comment by hhuijser** [comment]
@natecavanaugh 
Can you send me a pull with the modified .js, then I'll make the other changes and send to Brian.

**Comment by natecavanaugh** [comment]
Sent you one here: https://github.com/hhuijser/liferay-portal/pull/3152

**Pull request closed without merging**
