### PR TITLE
LPS-58905  Fix SF

### PR DESCRIPTION
**Pull request by carloslancha**
cc @jbalsas

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Hey guys,
I'm kicking this one back to you, because I think the way you're applying the indeterminate is going to break.
I think instead, we should get rid of the custom icon font hack for the checkboxes, as that styling only applies for when you're using the atlas theme, but so doing this indeterminate check for only certain browsers means it will still be broken in other browsers when using even just `_styled`.
I'm going to close this one out, but we can keep discussing it here, via email, or 
Slack, but I don't think the custom checkboxes are worth managing this way.
If you want to send over the other change for now, that's fine, but if we keep going down this path with the checkboxes, we'll be killing ourselves trying to support it properly for years.

Let me know what you guys think.

/cc @pat270 @marcoscv

**Comment by jbalsas** [comment]
Hey @natecavanaugh, I'm totally fine with trying to find a more solid solution.

In the meantime, I think you added the `:indeterminate` thing because of firefox, didn't you? Was it completely broken there, or just missing the icon? Do you think we can revert that so at least it works in Chrome and IE11 since QA already filed https://issues.liferay.com/browse/LPS-59658?

Then we can coordinate to find a better cross-browser solution.

What do you think?

**Comment by jbalsas** [comment]
Hey @natecavanaugh, in addition, I just remembered that @carloslancha mentioned that something in `search_container.js` could cause an exception (`currentValue` not being defined?). 

We have the symposium tomorrow and the day after, and won't get back to work until monday. Could you take care of pushing this to master (and remove the `indeterminate`) thing for us? We could try to find time during the event, but I'm not 100% sure we'll be able to :(

**Comment by pat270** [comment]
I agree with @natecavanaugh  about getting rid of the custom font hack from checkboxes. Chrome and webkit are the only browsers that really let you customize checkboxes via css. Firefox and IE have this weird variant that doesn't look anything like the original design. The only way we can really achieve consistently styled checkboxes across browsers (ie9+) is through a simplified version of checkbox card (http://liferay.github.io/lexicon/content/cards/#truncating-text-inside-horizontal-card-without-card-row-layout-fixed).

I think we should leave checkboxes in their native state and leave it up to our users to customize the form elements. We can provide documentation on how to do so.

**Comment by natecavanaugh** [comment]
Hey guys,
I'll go ahead and push this one in then, but we should remove it next week with a better solution (we'll work on the Lexicon side to remove the custom checkboxes stuff).

Thanks guys,

**Comment by natecavanaugh** [comment]
Merged and pushed to Brian. Thanks :)
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/31300
View total diff: https://github.com/natecavanaugh/liferay-portal/compare/189e648e60...8145ed9d2b

**Comment by jbalsas** [comment]
Thanks so much, Nate!

We'll start working on some related issues on monday. Should we involve @marcoscv so he can sync with you guys on the icon issue?

Let us know how it goes on the Lexicon side and what do you want us to do or if we can help with anything.

Thanks again!

**Comment by marcoscv-work** [comment]
Hey guys, sorry, I've been very busy with symposium's stuff.

On monday we can speak @jbalsas , I would like to try to help.

Thank guys.

**Comment by carloslancha** [comment]
Thank you all guys! On monday we'll try to find a better solution.

Have a good weekend!

**Pull request closed without merging**
