### PR TITLE
I give you... Tests!

### PR DESCRIPTION
**Pull request by brunobasto**
## JavaScript Tests

Last couple days I've been working on the javascript tests infrastructure for portal. The intent of this pull request is just to show you what I have so far and start a conversation. I'll try here to clarify some questions you might have when looking at the commits.
## Running the tests

To run the tests, you'll need `yeti`. Just go to portal-web and do:

portal-web: yeti

And that's it!

It'll generate coverage reports and everything:

HTML Reports:

http://cl.ly/image/3L1W3u340W46

http://cl.ly/image/0c293X3W3V0N

Plain Text Reports:

http://cl.ly/image/3E2t3I400G1p

Note: To generate the coverage reports, add the `-c` option the yeti command (`yeti -c`).

Note: I'm not sure we want to commit the generated coverage report files.

Hope you enjoy it :)

### CODE REVIEW

**Comment by natecavanaugh** [comment]
Hey guys,
I just wanted to see if you guys had discussed this any more since the retreat in Brazil.
@brunobasto you asked about the chances of getting Karma into Liferay, but after reading this thread, it seems like @ipeychev said he didn't think it would be a good fit given its architecture.
Has anything changed in that regard?
I guess the same would be for Testem as well, or any test runner, really.

Also, for this pull, is it usable to review as it currently is, or does it need to be updated?

Thanks Bruno!

**Comment by brunobasto** [comment]
Hey @natecavanaugh,

Regarding the code in this PR, I think we can just discard it. I know that currently @ipeychev is using Karma to test the Alloy Editor. I think that from his experience there, he can tell us if it would be a good fit for us. If so, I think we can reuse some of the code he's already written for his project. Specially the CI configurations and Sauce Labs stuff..

**Comment by ipeychev** [comment]
Yes, currently it is used in both AlloyEditor and in the new Alloy. Also, in both AlloyUI and AlloyEditor it is integrated with SauceLabs and we are executing the tests tests on IE9+, Chrome, Safari and FF. In AlloyUI they run on Android and iOS too. Check [here](https://github.com/alloyui/core) the status (on bottom of the page).
When I evaluated it, I found it is too different than Yeti and the way we wrote tests can't be directly applied to Karma. For example, we used to prepare special markup for the widgets directly into the HTML page, which was specific for each widget. Now, since we have just one page, we don't do that, but instead we create whatever is needed on the fly, via JS, i.e. we just adapted the test approach for Karma.

Why do you think we have to discard this PR, @brunobasto? What is wrong with it? Even if you was able to run the tests via Karma just on Chrome, it is still OK, I can then do the integration with SauceLabs.
If possible, better update it and let's go!

**Comment by brunobasto** [comment]
Hey @Iliyan, The reason I wanted to discard it is just because it was
written using Yeti. Also, the code is probably outdated since it's more
than 6 months old. I figured it was best to just create a new one. I have a
branch with tests running Karma on Chrome, FF, Safari. We can use that one.

Thanks,

**Comment by ipeychev** [comment]
Great - go ahead and then I will do the SauceLabs integration

**Comment by brunobasto** [comment]
Sent a new one to https://github.com/natecavanaugh/liferay-portal/pull/3169

**Pull request closed without merging**
